# 基本配置
title: Blog
description: Stylish Jekyll Theme
author:
  name: Rolyer Luo
  github: rolyer
  bio: This's My Tech Blog!

# 核心构建配置
github: [metadata]
paginate: 10
paginate_path: "page:num"
exclude: ["README.md", "vendor", "Gemfile", "Gemfile.lock"]

# 修正变量名：要么给它值，要么删掉。
# 建议给一个默认值防止 Liquid 报错
baseurl: "" 
url: "https://rolyer.github.io"

# 插件配置
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist

# 语法高亮
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 默认值
defaults:
  - scope:
      path: ""
    values:
      layout: post # 确保所有博文默认都有 layout
